---
- name: Copy env file
  copy:
    src: ./topology/mapping.env
    dest: ./mapping.env

- name: Remove old logs
  shell:
    cmd: truncate -s 0 /var/lib/docker/containers/*/*-json.log
    removes: /var/lib/docker/containers/*/*-json.log

- name: Pull image
  docker_image:
    name: "{{ docker_repo }}/{{ image_name }}"
    source: pull
    force_source: yes

- name: Start container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_repo }}/{{ image_name }}"
    state: started
    auto_remove: yes
    network_mode: host
    log_driver: journald
    env_file: ./mapping.env
