---
- name: Copy env file
  copy:
    src: files/mapping.env
    dest: /mapping.env

- name: Pull image
  docker_image:
    name: "{{ docker_repo }}/{{ image_name }}"
    source: pull
    force_source: yes

- name: Start container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_repo }}/{{ image_name }}"
    state: started
    auto_remove: yes
    log_driver: journald
    env_file: /mapping.env
    ports:
      - "{{ port }}:8080"
