---
- name: Update yum repositories and packages
  yum:
    name: "*"
    state: latest

- name: Install Python3.7
  yum:
    name: python37
    state: latest

- name: Install pip
  yum:
    name: python-pip
    state: latest

- name: Install Docker
  yum:
    name: docker
    state: latest

- name: Install Docker SDK
  pip:
    name: docker

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Kill all running docker containers
  shell: docker rm --force $(docker ps -aq) || true
